repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.14.2
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Stop commits to master
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]

  - repo: local
    hooks:
  
    - id: autoupdate
      name: autoupdate
      language: system  # Running on the local system
      stages: [push]
      verbose: true
      entry: pre-commit autoupdate
      pass_filenames: false

    - id: lint
      name: lint
      language: system  # Running on the local system
      stages: [commit, push]
      verbose: true
      entry: make lint
      types: [file, python]  # Only triggered if python files are changed in the commit
      pass_filenames: false
  
    - id: test
      name: test
      language: system  # Running on the local system
      stages: [push]
      verbose: true
      entry: make test
      types: [file, python]  # Only triggered if python files are changed in the commit
      pass_filenames: false
