name: Release

on:
  push:
    branches:
      - master

jobs:
    build_push:
      name: "Build & push Docker image"
      runs-on: ubuntu-latest
      if: "contains(github.event.head_commit.message, 'chore: bump version')"

      steps:
        - name: "Check out code"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        # This provides the repository name, as well as the latest
        # version which is used as a tag
        - name: "Get docker info"
          id: docker_info
          run: make docker-info
        
        - name: "Build & push"
          uses: docker/build-push-action@v1
          with:
            username: ${{  secrets.DOCKER_USERNAME }}
            password: ${{  secrets.DOCKER_TOKEN }}
            repository: ${{  steps.docker_info.outputs.docker_registry }}
            tags: latest, ${{  steps.docker_info.outputs.docker_tag }}
