name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
    build_push:
      name: Build & push Docker image
      runs-on: ubuntu-latest
      if: github.event.base_ref == 'refs/heads/master'

      steps:
        - name: Check out code
          uses: actions/checkout@v2.3.0
          with:
            fetch-depth: 0

        # This provides the repository name, the latest version
        # which is used as a tag, and the build system requirements
        - name: Get docker info
          id: docker_info
          run: make docker-info
        
        - name: Build & push
          uses: docker/build-push-action@v1
          with:
            username: ${{  secrets.DOCKER_USERNAME }}
            password: ${{  secrets.DOCKER_TOKEN }}
            repository: ${{  steps.docker_info.outputs.docker_registry }}
            tags: latest, ${{  steps.docker_info.outputs.docker_tag }}
            build_args: ${{ steps.docker_info.outputs.docker_build_args }}
